name: Create Text File

on:
  push:
    branches:
      - main

jobs:
  create_text_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a text file
        run: echo "Your text content here" > yourfile.txt

      - name: Commit and push
        run: |
          git config --local user.email "bilal.hassan7071@gmail.com"
          git config --local user.name "Bighra13"
          git add yourfile.txt
          git commit -m "Add new text file"
          git push
