name: FFMPEG and Git Push

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/1 * * * *' # Run every 5 minutes

jobs:
  ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install FFMPEG
        run: sudo apt update && sudo apt install ffmpeg -y
        
      - name: Run ffmpeg process
        run: |
          while true; do
            rm -f ptv0.ts
            ffmpeg -i http://starshare.live:8080/PTVSports/SportsPTV/61674 -c copy -f hls -hls_time 60 -hls_list_size 2 -hls_flags delete_segments ptv.m3u8
          done

  git_push:
    runs-on: ubuntu-latest
    needs: ffmpeg
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "bilal.hassan7071@gmail.com"
          git config --global user.name "Bighra13"

      - name: Add files
        run: git add ptv.m3u8 ptv0.ts

      - name: Commit files
        run: |
          git commit -m "Update live channel files"
          git push
