name: ptv3

on:
  push:
    branches:
      - main

jobs:
  ptv3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install ffmpeg
        run: sudo apt update && sudo apt install ffmpeg -y
      - name: Run ffmpeg process in background
        run: |
          rm -f ptv0.ts
          ffmpeg -i http://starshare.live:8080/PTVSports/SportsPTV/61674 -c copy -f hls -hls_time 30 -hls_list_size 2 -hls_flags delete_segments ptv.m3u8
