name: Create file

on:
  push:
    branches:
      - main

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: Create file
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.API_KEY}}
          script: |
            const fs = require('fs');
            const path = require('path');
            const filePath = path.join(process.env.GITHUB_WORKSPACE, 'example.txt');
            fs.writeFileSync(filePath, 'Hello, world!');
            github.rest.repos.createOrUpdateFile({
              path: 'example.txt',
              message: 'Create example.txt',
              content: fs.readFileSync(filePath, 'base64'),
              repo: context.repo,
              sha: context.sha
            });
