name: Push M3U8 File

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  push_m3u8_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up ffmpeg
        run: sudo apt update && sudo apt install ffmpeg -y

      - name: Run the script
        run: bash ./your_script.sh
