name: test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Cricket
    # timeout-minutes: 1 # Set the maximum duration for the job

    steps:
      - name: Update
        run: sudo apt update 
        
      - name: download rustDesk
        run: sudo wget https://github.com/rustdesk/rustdesk/releases/download/1.2.3/rustdesk-1.2.3-x86_64.deb
        
      - name: Install Missing Libraries
        run: sudo apt install -y zip g++ gcc git curl wget nasm yasm libgtk-3-dev clang libxcb-randr0-dev libxdo-dev libxfixes-dev libxcb-shape0-dev libxcb-xfixes0-dev libasound2-dev libpulse-dev cmake make libclang-dev ninja-build libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev -y
        
      - name: Install RustDesk
        run: sudo dpkg -i rustdesk-1.2.3-x86_64.deb

      - name: find details
        run: sudo rustdesk --info
        
      # - name: Install ffmpeg
      #   run: sudo apt update && sudo apt install ffmpeg -y
        
      # - name: Run the ffmpeg command
      #   run: ffmpeg -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 10 -i "http://starshare.live:8080/test2/2test/98" -vf "scale=-2:480" -c:v libx264 -c:a aac -f flv "rtmp://vsu.mycdn.me/input/6972982107673_6030686620185_untz7pm4gy"


      # - name: Trigger new workflow if canceled
      #   if: cancelled()
      #   run: |
      #     curl -X POST \
      #       -H "Authorization: token ${{ secrets.API_KEY }}" \
      #       -H "Accept: application/vnd.github.v3+json" \
      #       https://api.github.com/repos/${{ github.repository }}/actions/workflows/test.yml/dispatches \
      #       -d '{"ref":"main"}'
