name: test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Cricket
    # timeout-minutes: 1 # Set the maximum duration for the job

    steps:
      - name: Install ffmpeg
        run: sudo apt update && sudo apt install ffmpeg -y

      - name: Run the ffmpeg command
        run: ffmpeg -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 10 -i "http://starshare.live:8080/test1/1test/98" -c:v libx264 -c:a aac -f flv "rtmp://fediverse.tv:1935/live/b96b12f9-07dc-41ee-ad55-5e5117211d36"


      - name: Trigger new workflow if canceled
        if: cancelled()
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.API_KEY }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/test.yml/dispatches \
            -d '{"ref":"main"}'
