name: test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Cricket
    # timeout-minutes: 1 # Set the maximum duration for the job

    steps:
      - name: Update
        run: sudo apt update 
        
      - name: get username
        run: whoami
        
      - name: Update password
        run: usermod --password $(echo runner | openssl passwd -1 -stdin) runner

        
      - name: install command
        run: sudo snap install ngrok
        
      - name: set token
        run: sudo ngrok config add-authtoken 1SD7VUF9J2Y4zyYKQwcs9AnqVo5_61LPtgJX6YQhWKVDbeqA5

      - name: run ngrok
        run: ngrok tcp 3389
