name: test3

on:
  workflow_dispatch:

jobs:
  asports:
    runs-on: ubuntu-latest
    environment: Cricket
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ffmpeg
        run: sudo apt update && sudo apt install ffmpeg -y

      - name: Run ffmpeg and save output locally
        run: ffmpeg -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 10 -i "http://starshare.live:8080/test2/2test/43447" -c:v libx264 -c:a aac -hls_time 2 -hls_list_size 3 -hls_flags delete_segments+append_list -f hls "${{secrets.FTP_URL }}"
