name: ptvsports2

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  ptvsports2:
    runs-on: ubuntu-latest
    environment: Cricket
    # timeout-minutes: 1 # Set the maximum duration for the job

    steps:
      - name: Install ffmpeg
        run: sudo apt update && sudo apt install ffmpeg -y

      - name: Download remote bash file
        run: wget ${{secrets.PTV_SPORTS_URL }}

      - name: Install dos2unix
        run: sudo apt install dos2unix -y

      - name: Fix issue in downloaded file
        run: dos2unix ptv2.sh

      - name: Run the downloaded bash file
        run: bash ./ptv2.sh
